### ISSUE TITLE
Requesting attachment of document features

### ISSUE THREAD

**Issue by GanapathyAlagiri** [Ganapathy006/WhatsApp_Development#3]
Dear Ganapathy,

It would be great if the application is capable of attaching documents as well. Kindly add this feature.

**Comment by Ganapathy006** [comment]
Dear Gana,
Thanks for suggesting this feature. We will check and let you know.

**Comment by Ganapathy006** [comment]
Dear Gana,
Thanks for your valuable suggestion. This feature is going to make our product great.
